steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/angular-land-438802-e4/irene-100997763/assignment2:${COMMIT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/angular-land-438802-e4/irene-100997763/assignment2:${COMMIT_SHA}']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
